version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   depends_on:
  #   - db

  db: 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
    - "5434:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
